### ISSUE TITLE
Moving issue 

### ISSUE THREAD

**Issue by Yuvrajroy10** [Al3XKOoL/android_device_wiko_rainbow-WIP#11]
App are not moving to sd card 

How to fix this

**Comment by Adictya** [comment]
Try folder mount to move other things to SD card  moving apps to sd  is not supported in this rom

**Comment by Yuvrajroy10** [comment]
Please fix it

**Comment by Al3XKOoL** [comment]
We know this bug. Working on it.

**Comment by Al3XKOoL** [comment]
Fixed in the next build
