### ISSUE TITLE
Another issue (Offline Charge)

### ISSUE THREAD

**Issue by Yuvrajroy10** [Al3XKOoL/android_device_wiko_rainbow-WIP#13]
Some time my phone automatically restart. Why dude please help me to fix the problem

**Comment by Al3XKOoL** [comment]
Please attach logs and explain a bit. 

I never get random reboots.

**Comment by Yuvrajroy10** [comment]
Which log

**Comment by phantom-playR** [comment]
For me too, and when is connected to USB, it restart much more. http://pastebin.com/C21ieAY7

**Comment by Al3XKOoL** [comment]
This is caused because offline charge isn't working.

Not a random reboot.

We are working on fix it.

**Comment by phantom-playR** [comment]
ok, thank you.

**Comment by Al3XKOoL** [comment]
Fixed in the next release.
