### ISSUE TITLE
Usb mode is not coming

### ISSUE THREAD

**Issue by devilbs** [Al3XKOoL/android_device_wiko_rainbow-WIP#2]
guys when i first connected my device to my pc i select the option of only charging and now i wanted to transfer files notification is not coming of usb plugged in
it directly starts charging

**Comment by Al3XKOoL** [comment]
Not fix found for now sorry.

**Comment by gendouhydeist** [comment]
I think adding a config file for usb would fix this.
http://en.miui.com/thread-47348-1-1.html

As for me MTP and PTP works but for mass storage it doesn't work.

**Comment by Al3XKOoL** [comment]
Thanks, I'll try soon.

**Comment by l33tnoob** [comment]
For changing usb mode you can write following commands:
su
setprop persist.sys.usb.config mtp

for this command you should have Root access enabled in developer settings

**Comment by Al3XKOoL** [comment]
Usb "charge only" will be disabled as temp fix.

**Comment by aniruddha-adhikary** [comment]
These usb modes have something to do I guess!

https://github.com/Al3XKOoL/android_device_wiko_rainbow/blob/cm-12.1/rootdir/root/init.mt6582.usb.rc

**Comment by Klexer** [comment]
This is not a bug. The function is implemented differently in CM. There is a separate menu item for the USB connection under Settings / Storage. Please do not disable "charge only". USB-PC connect popup is an unstable Stock ROM feature, and not necessary for CyanogenMod.
![settings_storage](https://cloud.githubusercontent.com/assets/14591241/10122332/2a90bc44-6516-11e5-9dfb-df5baba6e38b.png)
![settings_storage_usb_connction](https://cloud.githubusercontent.com/assets/14591241/10122333/30a50a72-6516-11e5-9a5f-96ad3ad88916.png)

**Comment by Al3XKOoL** [comment]
We are talking about this menu option. If you put charge only can't go back to storage modes.

**Comment by Al3XKOoL** [comment]
Option disabled in the next release
