### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by zouuxx** [Al3XKOoL/android_device_wiko_rainbow-WIP#23]
When Toggle Wifi On 
Its Take Time To Turn On.

But when go to setting and Turn On Wifi, It  Start Immediately

**Comment by l33tnoob** [comment]
Can you record log of this issue?

**Comment by zouuxx** [comment]
Sry I Made A Mistake It Work Well
Can Mark This As Invalid

(It Was Just When Obtaining Ip Address It Take Around 10Sec)
