### ISSUE TITLE
SystemUI

### ISSUE THREAD

**Issue by zouuxx** [Al3XKOoL/android_device_wiko_rainbow-WIP#25]
Sometimes It Crash Then Restart By Itself

It Happened To Me Several Times

I Don't Know How, What Could Be The Reason,But Please Fix This Bug ,It Annoying

**Comment by zouuxx** [comment]
Hey It Happened Again
This Time I Know The Reason

When I Receive A Message From W.a 
SystemUI Crash And Restart To lock screen

**Comment by zouuxx** [comment]
W.a = Whatsapp

**Comment by Al3XKOoL** [comment]
With clean install you get same issue?

**Comment by zouuxx** [comment]
No
