### ISSUE TITLE
Cellular Network Not Available

### ISSUE THREAD

**Issue by zouuxx** [Al3XKOoL/android_device_wiko_rainbow-WIP#27]
When Press - or + Volume Button During Call It Say  "Cellular Network Not Available"
To Get Call Working Again Need To Format Phone

**Comment by aniruddha-adhikary** [comment]
I assume something's up with the NVRAM stuff, since the volume status are usually written in the NVRAM

**Comment by zouuxx** [comment]
Can You Fixed  It ?

**Comment by Al3XKOoL** [comment]
We are working on it

**Comment by aniruddha-adhikary** [comment]
I went through the logs, and found out that the RIL stops and restarts when calls are initiated.

https://github.com/xen0n/android_frameworks_opt_telephony_mtk/commit/7f7b9eb7f2bb61b8e7a74111cd1fc03e0932d28c

**Comment by arvinquilao** [comment]
@Al3XKOoL Did you try and test xen0n's commit? I don't have time yet to recompile and test telephony-common.jar. Here's my radio log, in case you're interested: https://www.dropbox.com/s/mugf76bfo5af6oj/logcat_radio.log?dl=0

**Comment by Al3XKOoL** [comment]
Fixed in the next release
