### ISSUE TITLE
Headphone

### ISSUE THREAD

**Issue by zouuxx** [Al3XKOoL/android_device_wiko_rainbow-WIP#28]
Headphone Icon Are Not Displaying When Plugged In

**Comment by Al3XKOoL** [comment]
It's only cosmetic thing, headset is working well.

**Comment by zouuxx** [comment]
Ok.
It Will Be Great If You Can Make The Icon Appear (Just A Request)

**Comment by Al3XKOoL** [comment]
You can use playstore apps like this:
https://play.google.com/store/apps/details?id=com.susomena.headphonesindicator&hl=en

**Comment by zouuxx** [comment]
Ok 
Thanks
