### ISSUE TITLE
Phone switches Of

### ISSUE THREAD

**Issue by Adictya** [Al3XKOoL/android_device_wiko_rainbow-WIP#30]
Sometimes when there is an incoming call the phone would reboot and the incoming call is not even gets listed in the call logs and if not reboots the handset hangs everytime there is an incoming call

PLEASE FIX!!!

**Comment by Al3XKOoL** [comment]
Can you attach logs? 

I can't reproduce this error.

**Comment by Adictya** [comment]
How silly of me I forgot the logs 
This hasn't happened since a long time I'll send with logs the next time it happens till then close it
Thanks for your concern
