### ISSUE TITLE
Hot device when playing video through WiFi

### ISSUE THREAD

**Issue by fagci** [Al3XKOoL/android_device_wiko_rainbow-WIP#35]
Is there builtin internet sppeedify tweak, same as init.d tweak?
Consumes battery drain and burning device..

**Comment by Al3XKOoL** [comment]
Battery backup seems to be better than in other roms.

I used CleanKat long ago, Now i can say my battery is better than CleanKat.
I used same apps with same scenario in both roms.

Can you explain how your battery is drained?

EDIT:
My device temp seem like to stock rom.

**Comment by fagci** [comment]
Playing YouTube videos through their own application, approx. 20% / 30min drain.
Maybe, it can be fixed with build.prop network tweaks: low speed, less drain and fantoms on my ZOPO zp980+
My device so hot after 20..30min videos playing, sometimes connection looses after that..

**Comment by Al3XKOoL** [comment]
Can you share these tweaks?

**Comment by fagci** [comment]
``` shell
# NetSpeed tweaks
net.tcp.buffersize.default=4096,87380,256960,4096,16384,256960
net.tcp.buffersize.wifi=4096,87380,256960,4096,16384,256960
net.tcp.buffersize.umts=4096,87380,256960,4096,16384,256960
net.tcp.buffersize.gprs=4096,87380,256960,4096,16384,256960
net.tcp.buffersize.edge=4096,87380,256960,4096,16384,256960
```

With this settings more battery drain, more heat, but we can reduce this

**Comment by Al3XKOoL** [comment]
The device is also heated with stock rom.

It's not a ROM problem.
