### ISSUE TITLE
Building the Repo fails during "lunch" step -> Missing device spec?

### ISSUE THREAD

**Issue by stephan48** [Al3XKOoL/android_device_wiko_rainbow-WIP#37]
Hi,

Thank you for your good work!

I am trying to build a current version of this tree.
I folllowed the Instructions for installing repo and the toolchain but then i got the following error:

$ lunch cm_rainbow-eng
build/core/product_config.mk:234: **\* Can not locate config makefile for product "cm_rainbow".  Stop.
Device rainbow not found. Attempting to retrieve device repository from CyanogenMod Github (http://github.com/CyanogenMod).
Repository for rainbow not found in the CyanogenMod Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:234: **\* Can not locate config makefile for product "cm_rainbow".  Stop.

*\* Don't have a product spec for: 'cm_rainbow'
*\* Do you have the right repo manifest?

Which step am I missing?

Kind Regards,
Stephan

**Comment by fagci** [comment]
Stephan, what you need to do:
`repo sync`

then you get overall tools for building CM on any device, but you need also
`git pull <device repo> device/<device_manufacturer>/<model>/`
`git pull <vendor repo> vendor/<device_manufacturer>/<model>/`.

To make proper config, make changes close to sample `*.mk` files in `device/* vendor/*` folders.

Google samples for other devices.

Do not forget to `source build/envsetup.sh` before `lunch`

If you have some warnings about manifests, try to `make` anyway

**Comment by stephan48** [comment]
Hi,

Thanks that provided the informations i needed :)
It actually makes quite a bit of sense!

KInd Regards,
Stephan
