### ISSUE TITLE
Buildfailure during compilation of GPS classes

### ISSUE THREAD

**Issue by stephan48** [Al3XKOoL/android_device_wiko_rainbow-WIP#40]
Hi again,

When i try to build the source(latest device and vendor repo; CM 12.1) for this rom i get this error:

frameworks/base/services/core/jni/com_android_server_location_GpsLocationProvider.cpp:165:1: error: invalid conversion from 'void (_)(GpsUtcTime, const char_, int) {aka void (_)(long long int, const char_, int)}' to 'gnss_sv_status_callback {aka void (_)(GnssSvStatus_)}' [-fpermissive]
 };
 ^
frameworks/base/services/core/jni/com_android_server_location_GpsLocationProvider.cpp:165:1: error: invalid conversion from 'void (_)(uint32_t) {aka void (_)(unsigned int)}' to 'gps_nmea_callback {aka void (_)(long long int, const char_, int)}' [-fpermissive]
frameworks/base/services/core/jni/com_android_server_location_GpsLocationProvider.cpp:165:1: error: invalid conversion from 'void (_)()' to 'gps_set_capabilities {aka void (_)(unsigned int)}' [-fpermissive]
frameworks/base/services/core/jni/com_android_server_location_GpsLocationProvider.cpp:165:1: error: invalid conversion from 'pthread_t (_)(const char_, void (_)(void_), void_) {aka long int (_)(const char_, void (_)(void_), void_)}' to 'gps_release_wakelock {aka void (_)()}' [-fpermissive]
frameworks/base/services/core/jni/com_android_server_location_GpsLocationProvider.cpp:165:1: error: invalid conversion from 'void (_)()' to 'gps_create_thread {aka long int (_)(const char_, void (_)(void_), void_)}' [-fpermissive]
frameworks/base/services/core/jni/com_android_server_location_GpsLocationProvider.cpp:165:1: warning: missing initializer for member 'GpsCallbacks::request_utc_time_cb' [-Wmissing-field-initializers]
build/core/binary.mk:619: recipe for target '/home/androidrom/rainbowbuild/out/target/product/rainbow/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/core/jni/com_android_server_location_GpsLocationProvider.o' failed
make: *_\* [/home/androidrom/rainbowbuild/out/target/product/rainbow/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/core/jni/com_android_server_location_GpsLocationProvider.o] Error 1

Is there a easy fix i could apply?

Kind Regards,
Stephan

**Comment by fagci** [comment]
same issue here =(

**Comment by Al3XKOoL** [comment]
You have applied gps patches in sources?

**Comment by stephan48** [comment]
Hi,
I did straight out builds from source:

$ #install repo tool
$ repo init -u git://github.com/CyanogenMod/android.git -b cm-12.1
$ repo sync
$ mkdir {device,vendor}/wiko/
$ git clone https://github.com/Al3XKOoL/android_device_wiko_rainbow device/wiko/rainbow/
$ git clone https://github.com/Al3XKOoL/android_vendor_wiko_rainbow vendor/wiko/rainbow/
$ source build/envsetup.sh
$ brunch cm_rainbow-eng

It runs for a few hours and then spits out an error.

Am i missing some steps?

Kind Regards,
Stephan

PS: I got absolutely no experience with building android roms :)

**Comment by Al3XKOoL** [comment]
You need look at @fire855 repo.

**Comment by stephan48** [comment]
Can you give me a direct link please?
I can't seem to find a wiko rainbow repo in his account..

**Comment by fire855** [comment]
Are you using my frameworks_base?
You need this commit: https://github.com/fire855/android_frameworks_base-mt6592/commit/6b391f3556fe9ec1231fe2a71d66766f36dc23f1

**Comment by stephan48** [comment]
No. Where would the frameworks_base go into the whole buildtree?

**Comment by arvinquilao** [comment]
You apply those commits to your own frameworks_base repo.
