### ISSUE TITLE
Online games can't be played...

### ISSUE THREAD

**Issue by md-redwan-hossain** [Al3XKOoL/android_device_wiko_rainbow-WIP#46]
I cannot play clash of clans,8 ball pool etc... always forced closed problem... fix it plz.

**Comment by ponnex** [comment]
Games are working fine excepts for those that need obb. Obb doesn't work on this build but I hope it will :D

**Comment by Al3XKOoL** [comment]
I can play clash of clans and other games. 

Share logs and wath device are you using.

**Comment by md-redwan-hossain** [comment]
#COC fixed.
But can't  play HD games like GTA SA, Dead Trigger, COD ST....

**Comment by Al3XKOoL** [comment]
How fix clash of clans? For me is working without changes.

Please share logs with games errors.

**Comment by md-redwan-hossain** [comment]
Obb file needed game issue fixed. . just install the latest one from play store.. But sometimes I get auto reboot if I play CPC more than 10 min continually..
