### ISSUE TITLE
Low call speaker volume, very low

### ISSUE THREAD

**Issue by vladuhin** [Al3XKOoL/android_device_wiko_rainbow-WIP#47]
This bug not always appears after watching video throught YouTube app, playing games, if i change multimedia volume while watching or listening something thats all almost usually create this bug. Reboot the phone or turn on and off airplane mode fix this problem.
I can give you logs when bug is on and when all's fine

**Comment by sinha500** [comment]
same i also facing... rebooting solving this problem temporarily ...

**Comment by ponnex** [comment]
same here, in fact this issue is also on cm12.1 Kingzone K1 Turbo by fire855. Initial investigation/test and which has been tested by me was gapps issue. Try flashing the ROM without gapps and test it for awhile, 1-2 days maybe like what I did, there won't be any in-call issue, then flash gapps afterwards, the issue will then be there. Hope this works ;)

**Comment by vladuhin** [comment]
I can't use my phone withous gapps and besides turn on and off airplane mode fix this problem, for a while.

**Comment by joysurjo** [comment]
tried flashing without gapps but its not working.

**Comment by ponnex** [comment]
Does this relates to this issue? this always shows and repeat at logcat

![screenshot_2015-11-26-13-03-23](https://cloud.githubusercontent.com/assets/10062054/11453214/efc002f2-963c-11e5-8a1f-702466af96bd.png)

**Comment by ponnex** [comment]
11-29 01:56:03.557   512   694 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client

11-29 01:56:03.633   146   552 E AudioFlinger: getNextBuffer, get null buffer

11-29 01:56:04.858   512  1059 W InputMethodManagerService: Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@2d72dcfd (uid=10061 pid=3686)

11-29 01:56:06.650   146   552 E         : AudioCloseDumpPCMFile file== NULL

11-29 01:56:06.650   146   552 E         : AudioCloseDumpPCMFile file== NULL

11-29 01:56:06.650   146   552 E         : AudioCloseDumpPCMFile file== NULL

11-29 01:56:06.650   146   552 E         : AudioCloseDumpPCMFile file== NULL

**Comment by ponnex** [comment]
OMXCodex errors

11-29 02:03:28.554   146  4484 E OMXNodeInstance: getConfig(2a:google.vorbis.decoder, ??(0x7f00001b)) ERROR: Undefined(0x80001001)

11-29 02:03:28.581   146  4487 E OMXCodec: [OMX.google.vorbis.decoder] No more output data in fillOutputBuffer, mFilledBuffers size=1

11-29 02:03:28.581   146  4487 E OMXCodec: [OMX.google.vorbis.decoder] No more output data in fillOutputBuffer, mFilledBuffers size=0

11-29 02:03:28.581   146  4487 E OMXCodec: [OMX.google.vorbis.decoder] read() final return

**Comment by Al3XKOoL** [comment]
Fixed in the next release.
