### ISSUE TITLE
Some games didnt work in last build

### ISSUE THREAD

**Issue by vladuhin** [Al3XKOoL/android_device_wiko_rainbow-WIP#50]
I have GTA SA, Dead Trigger 2 go to FC, Call of Duty Heroes - freezing after 10 sec gameplay, ofcourse this is not full list
After FC or freeze, i see in logcat tons of errors and warnings about audiopolicy, audiomanager, etc. and google.gms. 
Will this be fixed? In previous beta 4 build thats all is working like a clock, better in kitkat

**Comment by Al3XKOoL** [comment]
Duplicated https://github.com/Al3XKOoL/android_device_wiko_rainbow/issues/46
