### ISSUE TITLE
No vpn working

### ISSUE THREAD

**Issue by md-redwan-hossain** [Al3XKOoL/android_device_wiko_rainbow-WIP#53]
I tried 20+ vpn app from play store, none of them working.. 
Can't play any HD games which needs obb file like dead trigger,GTA SA, COD ST etc

**Comment by ponnex** [comment]
You have already posted an issue about games, so this might be about VPN? maybe rename and change this one. VPN does work on the previous build but on the latest it does not

**Comment by Al3XKOoL** [comment]
Games report is here: https://github.com/Al3XKOoL/android_device_wiko_rainbow/issues/46

Can you share logs from vpn testing?

**Comment by ponnex** [comment]
E/ (3686): appName=com.psiphone3,acAppName=/system/bin/surfaceflinger

error on psiphon "Check tunnel failed. Your device may bot support the whole device tunner option."
"Root mode is not supported on this version of Android".

**Comment by ponnex** [comment]
![screenshot_2015-11-29-02-09-43](https://cloud.githubusercontent.com/assets/10062054/11453255/a8624594-963e-11e5-924d-1a3b2b7ea1c6.png)
![screenshot_2015-11-29-02-11-25](https://cloud.githubusercontent.com/assets/10062054/11453256/a89546c4-963e-11e5-91df-c4dade15de14.png)
![screenshot_2015-11-29-02-11-08](https://cloud.githubusercontent.com/assets/10062054/11453257/a8b73ea0-963e-11e5-942b-579a0b3666a5.png)

**Comment by ponnex** [comment]
This is the logcat I got when I turn on VPN on Psiphon3

11-29 01:55:55.362   512   756 I Vpn     : Established by com.psiphon3 on tun0

11-29 01:55:55.508   143   468 E Netd    : netlink response contains error (Invalid argument)

11-29 01:55:55.508   143   468 E Netd    : failed to add interface tun0 to VPN netId 101

11-29 01:55:55.509   512   689 E ConnectivityService: Exception adding interface: java.lang.IllegalStateException: command '58 network interface add 101 tun0' failed with '400 58 addInterfaceToNetwork() failed (Invalid argument)'

11-29 01:55:55.509   512   689 E ConnectivityService: Unexpected mtu value: 0, tun0

11-29 01:55:55.510   143   468 E Netd    : interface tun0 not assigned to any netId

11-29 01:55:55.511   512   689 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '59 network route add 101 tun0 0.0.0.0/0' failed with '400 59 addRoute() failed (No such device)'

11-29 01:55:55.512   143   468 E Netd    : interface tun0 not assigned to any netId

11-29 01:55:55.512   512   689 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '60 network route add 101 tun0 10.0.0.0/8' failed with '400 60 addRoute() failed (No such device)'

11-29 01:55:55.513   143   468 E Netd    : interface tun0 not assigned to any netId

11-29 01:55:55.544   159   159 E agps    : ERR: [MNL2AGPS] sendto dest=[/data/agps_supl/mnl_to_agps] len=26 reason=[No such file or directory]

11-29 01:55:55.544   159   159 E agps    : ERR: [MNL2AGPS] external_snd_cmd safe_sendto failed

11-29 01:55:55.546   159   159 E agps    : ERR: [MNL2AGPS] sendto dest=[/data/agps_supl/mnl_to_agps] len=27 reason=[No such file or directory]

11-29 01:55:55.546   159   159 E agps    : ERR: [MNL2AGPS] external_snd_cmd safe_sendto failed

11-29 01:55:55.557   512   689 E ConnectivityService: Attempting to register duplicate agent for type 17: NetworkAgentInfo{ ni{[type: VPN[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]}  network{101}  lp{{InterfaceName: tun0 LinkAddresses: [10.0.0.1/8,]  Routes: [0.0.0.0/0 -> 0.0.0.0 tun0,10.0.0.0/8 -> 0.0.0.0 tun0,::/0 unreachable,] DnsAddresses: [10.0.0.2,] Domains:  MTU: 0}}  nc{[ Transports: VPN Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED]}  Score{0}  everValidated{true}  lastValidated{true}  created{true}  explicitlySelected{false} }

11-29 01:55:55.603  1521  1521 I UpdateCheckReceiver: Got connectivity change, has connection: true

11-29 01:55:55.603  1521  1521 I UpdateCheckReceiver: Scheduling future, repeating update checks.

**Comment by Al3XKOoL** [comment]
Can you test with this VpnROOT?
https://play.google.com/store/apps/details?id=com.did.vpnroot&hl=es

**Comment by md-redwan-hossain** [comment]
opening a new issue.. check that plz
