### ISSUE TITLE
The bl

### ISSUE THREAD

**Issue by DarwishCodes** [Al3XKOoL/android_device_wiko_rainbow-WIP#83]

**Comment by Al3XKOoL** [comment]
Can you explain the problem?

**Comment by DarwishCodes** [comment]
I have really something annoying me and it is the bluetooth headphone in cm12.1 , when i connect my bluetooth headphone to the device , and i go the youtube and watch a video or something the , the sound begins to crackle , an the sound is not playing with the video.
Could you fix that bug , that annoying bug , that is the only bug that is left.

-Regards.
