### ISSUE TITLE
Facebook messenger bug [VoIP Calls]

### ISSUE THREAD

**Issue by mrdarkus** [Al3XKOoL/android_device_wiko_rainbow-WIP#9]
When i try to make a call in facebook messenger it fails i hope you will fix it

**Comment by Al3XKOoL** [comment]
Voip call isn't working for now.

**Comment by Klexer** [comment]
I found out VoIP issues are caused by microphone. When using FRITZ!App Fon, I can fix it by Settings / Advanced / Alternative Microphone. Microphone bug #22 is closed. Shouldn't FB messenger bug #9 also be fixed now?

**Comment by Al3XKOoL** [comment]
Sorry i miss it.
Fixed in the next release
